# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
PCH = Source/pch.hpp
PCH_PLACEHOLDER = $(OBJDIR)/$(notdir $(PCH))
GCH = $(PCH_PLACEHOLDER).gch
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug)
TARGETDIR = Bin/Debug-linux-x86_64/Enigma
TARGET = $(TARGETDIR)/Enigma
OBJDIR = Bin-Intermediate/Debug-linux-x86_64/Enigma
DEFINES += -DENIGMA_PLATFORM_LINUX -DENIGMA_DEBUG
INCLUDES += -ISource -IDependencies/glfw/include -IDependencies/glad/include -IDependencies/imgui -IDependencies/spdlog/include -IDependencies/pfd/include -IDependencies/stb_image/include -IDependencies/cxxopts/include -IDependencies/cryptopp -IDependencies/inih/include -IDependencies/json/include -IDependencies/sqlitecpp/include -IDependencies/curl/include -IDependencies/cpr/include -IDependencies/tabulate/include -IDependencies/infoware/include -IDependencies/catch2/src
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -Wall -Wextra -std=c++17
LIBS += Dependencies/glfw/Bin/Debug-linux-x86_64/glfw/libglfw.a Dependencies/glad/Bin/Debug-linux-x86_64/glad/libglad.a Dependencies/imgui/Bin/Debug-linux-x86_64/imgui/libimgui.a Dependencies/spdlog/Bin/Debug-linux-x86_64/spdlog/libspdlog.a Dependencies/pfd/Bin/Debug-linux-x86_64/pfd/libpfd.a Dependencies/stb_image/Bin/Debug-linux-x86_64/stb_image/libstb_image.a Dependencies/cxxopts/Bin/Debug-linux-x86_64/cxxopts/libcxxopts.a Dependencies/cryptopp/Bin/Debug-linux-x86_64/cryptopp/libcryptopp.a Dependencies/inih/Bin/Debug-linux-x86_64/inih/libinih.a Dependencies/json/Bin/Debug-linux-x86_64/json/libjson.a Dependencies/sqlitecpp/Bin/Debug-linux-x86_64/sqlitecpp/libsqlitecpp.a Dependencies/cpr/Bin/Debug-linux-x86_64/cpr/libcpr.a Dependencies/curl/Bin/Debug-linux-x86_64/curl/libcurl.a Dependencies/tabulate/Bin/Debug-linux-x86_64/tabulate/libtabulate.a Dependencies/infoware/Bin/Debug-linux-x86_64/infoware/libinfoware.a Dependencies/zlib/Bin/Debug-linux-x86_64/zlib/libzlib.a Dependencies/mbedtls/Bin/Debug-linux-x86_64/mbedtls/libmbedtls.a Dependencies/catch2/Bin/Debug-linux-x86_64/catch2/libcatch2.a -lGL -lX11 -lXrandr -ldl -lpthread -lstdc++fs -ltbb
LDDEPS += Dependencies/glfw/Bin/Debug-linux-x86_64/glfw/libglfw.a Dependencies/glad/Bin/Debug-linux-x86_64/glad/libglad.a Dependencies/imgui/Bin/Debug-linux-x86_64/imgui/libimgui.a Dependencies/spdlog/Bin/Debug-linux-x86_64/spdlog/libspdlog.a Dependencies/pfd/Bin/Debug-linux-x86_64/pfd/libpfd.a Dependencies/stb_image/Bin/Debug-linux-x86_64/stb_image/libstb_image.a Dependencies/cxxopts/Bin/Debug-linux-x86_64/cxxopts/libcxxopts.a Dependencies/cryptopp/Bin/Debug-linux-x86_64/cryptopp/libcryptopp.a Dependencies/inih/Bin/Debug-linux-x86_64/inih/libinih.a Dependencies/json/Bin/Debug-linux-x86_64/json/libjson.a Dependencies/sqlitecpp/Bin/Debug-linux-x86_64/sqlitecpp/libsqlitecpp.a Dependencies/cpr/Bin/Debug-linux-x86_64/cpr/libcpr.a Dependencies/curl/Bin/Debug-linux-x86_64/curl/libcurl.a Dependencies/tabulate/Bin/Debug-linux-x86_64/tabulate/libtabulate.a Dependencies/infoware/Bin/Debug-linux-x86_64/infoware/libinfoware.a Dependencies/zlib/Bin/Debug-linux-x86_64/zlib/libzlib.a Dependencies/mbedtls/Bin/Debug-linux-x86_64/mbedtls/libmbedtls.a Dependencies/catch2/Bin/Debug-linux-x86_64/catch2/libcatch2.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64
define POSTBUILDCMDS
	@echo Copying ./Resources dir to Bin/Debug-linux-x86_64/Enigma/ ...
	cp -rf Resources Bin/Debug-linux-x86_64/Enigma/Resources
endef

else ifeq ($(config),release)
TARGETDIR = Bin/Release-linux-x86_64/Enigma
TARGET = $(TARGETDIR)/Enigma
OBJDIR = Bin-Intermediate/Release-linux-x86_64/Enigma
DEFINES += -DENIGMA_PLATFORM_LINUX -DENIGMA_RELEASE
INCLUDES += -ISource -IDependencies/glfw/include -IDependencies/glad/include -IDependencies/imgui -IDependencies/spdlog/include -IDependencies/pfd/include -IDependencies/stb_image/include -IDependencies/cxxopts/include -IDependencies/cryptopp -IDependencies/inih/include -IDependencies/json/include -IDependencies/sqlitecpp/include -IDependencies/curl/include -IDependencies/cpr/include -IDependencies/tabulate/include -IDependencies/infoware/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O2 -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O2 -Wall -Wextra -std=c++17
LIBS += Dependencies/glfw/Bin/Release-linux-x86_64/glfw/libglfw.a Dependencies/glad/Bin/Release-linux-x86_64/glad/libglad.a Dependencies/imgui/Bin/Release-linux-x86_64/imgui/libimgui.a Dependencies/spdlog/Bin/Release-linux-x86_64/spdlog/libspdlog.a Dependencies/pfd/Bin/Release-linux-x86_64/pfd/libpfd.a Dependencies/stb_image/Bin/Release-linux-x86_64/stb_image/libstb_image.a Dependencies/cxxopts/Bin/Release-linux-x86_64/cxxopts/libcxxopts.a Dependencies/cryptopp/Bin/Release-linux-x86_64/cryptopp/libcryptopp.a Dependencies/inih/Bin/Release-linux-x86_64/inih/libinih.a Dependencies/json/Bin/Release-linux-x86_64/json/libjson.a Dependencies/sqlitecpp/Bin/Release-linux-x86_64/sqlitecpp/libsqlitecpp.a Dependencies/cpr/Bin/Release-linux-x86_64/cpr/libcpr.a Dependencies/curl/Bin/Release-linux-x86_64/curl/libcurl.a Dependencies/tabulate/Bin/Release-linux-x86_64/tabulate/libtabulate.a Dependencies/infoware/Bin/Release-linux-x86_64/infoware/libinfoware.a Dependencies/zlib/Bin/Release-linux-x86_64/zlib/libzlib.a Dependencies/mbedtls/Bin/Release-linux-x86_64/mbedtls/libmbedtls.a -lGL -lX11 -lXrandr -ldl -lpthread -lstdc++fs -ltbb
LDDEPS += Dependencies/glfw/Bin/Release-linux-x86_64/glfw/libglfw.a Dependencies/glad/Bin/Release-linux-x86_64/glad/libglad.a Dependencies/imgui/Bin/Release-linux-x86_64/imgui/libimgui.a Dependencies/spdlog/Bin/Release-linux-x86_64/spdlog/libspdlog.a Dependencies/pfd/Bin/Release-linux-x86_64/pfd/libpfd.a Dependencies/stb_image/Bin/Release-linux-x86_64/stb_image/libstb_image.a Dependencies/cxxopts/Bin/Release-linux-x86_64/cxxopts/libcxxopts.a Dependencies/cryptopp/Bin/Release-linux-x86_64/cryptopp/libcryptopp.a Dependencies/inih/Bin/Release-linux-x86_64/inih/libinih.a Dependencies/json/Bin/Release-linux-x86_64/json/libjson.a Dependencies/sqlitecpp/Bin/Release-linux-x86_64/sqlitecpp/libsqlitecpp.a Dependencies/cpr/Bin/Release-linux-x86_64/cpr/libcpr.a Dependencies/curl/Bin/Release-linux-x86_64/curl/libcurl.a Dependencies/tabulate/Bin/Release-linux-x86_64/tabulate/libtabulate.a Dependencies/infoware/Bin/Release-linux-x86_64/infoware/libinfoware.a Dependencies/zlib/Bin/Release-linux-x86_64/zlib/libzlib.a Dependencies/mbedtls/Bin/Release-linux-x86_64/mbedtls/libmbedtls.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -s
define POSTBUILDCMDS
	@echo Copying ./Resources dir to Bin/Release-linux-x86_64/Enigma/ ...
	cp -rf Resources Bin/Release-linux-x86_64/Enigma/Resources
endef

else ifeq ($(config),dist)
TARGETDIR = Bin/Dist-linux-x86_64/Enigma
TARGET = $(TARGETDIR)/Enigma
OBJDIR = Bin-Intermediate/Dist-linux-x86_64/Enigma
DEFINES += -DENIGMA_PLATFORM_LINUX -DENIGMA_DIST
INCLUDES += -ISource -IDependencies/glfw/include -IDependencies/glad/include -IDependencies/imgui -IDependencies/spdlog/include -IDependencies/pfd/include -IDependencies/stb_image/include -IDependencies/cxxopts/include -IDependencies/cryptopp -IDependencies/inih/include -IDependencies/json/include -IDependencies/sqlitecpp/include -IDependencies/curl/include -IDependencies/cpr/include -IDependencies/tabulate/include -IDependencies/infoware/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -Wall -Wextra -std=c++17
LIBS += Dependencies/glfw/Bin/Dist-linux-x86_64/glfw/libglfw.a Dependencies/glad/Bin/Dist-linux-x86_64/glad/libglad.a Dependencies/imgui/Bin/Dist-linux-x86_64/imgui/libimgui.a Dependencies/spdlog/Bin/Dist-linux-x86_64/spdlog/libspdlog.a Dependencies/pfd/Bin/Dist-linux-x86_64/pfd/libpfd.a Dependencies/stb_image/Bin/Dist-linux-x86_64/stb_image/libstb_image.a Dependencies/cxxopts/Bin/Dist-linux-x86_64/cxxopts/libcxxopts.a Dependencies/cryptopp/Bin/Dist-linux-x86_64/cryptopp/libcryptopp.a Dependencies/inih/Bin/Dist-linux-x86_64/inih/libinih.a Dependencies/json/Bin/Dist-linux-x86_64/json/libjson.a Dependencies/sqlitecpp/Bin/Dist-linux-x86_64/sqlitecpp/libsqlitecpp.a Dependencies/cpr/Bin/Dist-linux-x86_64/cpr/libcpr.a Dependencies/curl/Bin/Dist-linux-x86_64/curl/libcurl.a Dependencies/tabulate/Bin/Dist-linux-x86_64/tabulate/libtabulate.a Dependencies/infoware/Bin/Dist-linux-x86_64/infoware/libinfoware.a Dependencies/zlib/Bin/Dist-linux-x86_64/zlib/libzlib.a Dependencies/mbedtls/Bin/Dist-linux-x86_64/mbedtls/libmbedtls.a -lGL -lX11 -lXrandr -ldl -lpthread -lstdc++fs -ltbb
LDDEPS += Dependencies/glfw/Bin/Dist-linux-x86_64/glfw/libglfw.a Dependencies/glad/Bin/Dist-linux-x86_64/glad/libglad.a Dependencies/imgui/Bin/Dist-linux-x86_64/imgui/libimgui.a Dependencies/spdlog/Bin/Dist-linux-x86_64/spdlog/libspdlog.a Dependencies/pfd/Bin/Dist-linux-x86_64/pfd/libpfd.a Dependencies/stb_image/Bin/Dist-linux-x86_64/stb_image/libstb_image.a Dependencies/cxxopts/Bin/Dist-linux-x86_64/cxxopts/libcxxopts.a Dependencies/cryptopp/Bin/Dist-linux-x86_64/cryptopp/libcryptopp.a Dependencies/inih/Bin/Dist-linux-x86_64/inih/libinih.a Dependencies/json/Bin/Dist-linux-x86_64/json/libjson.a Dependencies/sqlitecpp/Bin/Dist-linux-x86_64/sqlitecpp/libsqlitecpp.a Dependencies/cpr/Bin/Dist-linux-x86_64/cpr/libcpr.a Dependencies/curl/Bin/Dist-linux-x86_64/curl/libcurl.a Dependencies/tabulate/Bin/Dist-linux-x86_64/tabulate/libtabulate.a Dependencies/infoware/Bin/Dist-linux-x86_64/infoware/libinfoware.a Dependencies/zlib/Bin/Dist-linux-x86_64/zlib/libzlib.a Dependencies/mbedtls/Bin/Dist-linux-x86_64/mbedtls/libmbedtls.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -s
define POSTBUILDCMDS
	@echo Copying ./Resources dir to Bin/Dist-linux-x86_64/Enigma/ ...
	cp -rf Resources Bin/Dist-linux-x86_64/Enigma/Resources
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/AES.o
GENERATED += $(OBJDIR)/Algorithm.o
GENERATED += $(OBJDIR)/Application.o
GENERATED += $(OBJDIR)/Base64.o
GENERATED += $(OBJDIR)/Blowfish.o
GENERATED += $(OBJDIR)/CLI.o
GENERATED += $(OBJDIR)/CPUInfo.o
GENERATED += $(OBJDIR)/ChaCha20Poly1305.o
GENERATED += $(OBJDIR)/Clipboard.o
GENERATED += $(OBJDIR)/Config.o
GENERATED += $(OBJDIR)/Cursor.o
GENERATED += $(OBJDIR)/Database.o
GENERATED += $(OBJDIR)/DecryptFileScene.o
GENERATED += $(OBJDIR)/DecryptTextScene.o
GENERATED += $(OBJDIR)/ENV.o
GENERATED += $(OBJDIR)/EncryptFileScene.o
GENERATED += $(OBJDIR)/EncryptTextScene.o
GENERATED += $(OBJDIR)/GZip.o
GENERATED += $(OBJDIR)/HashingTool.o
GENERATED += $(OBJDIR)/IDEA.o
GENERATED += $(OBJDIR)/ImGuiImpl.o
GENERATED += $(OBJDIR)/ImGuiRenderer.o
GENERATED += $(OBJDIR)/Input.o
GENERATED += $(OBJDIR)/LoadingScene.o
GENERATED += $(OBJDIR)/Logger.o
GENERATED += $(OBJDIR)/Main.o
GENERATED += $(OBJDIR)/MainMenuScene.o
GENERATED += $(OBJDIR)/MessageBox.o
GENERATED += $(OBJDIR)/MyEncryptionsScene.o
GENERATED += $(OBJDIR)/Notification.o
GENERATED += $(OBJDIR)/OpenFileDialog.o
GENERATED += $(OBJDIR)/PasswordGeneratorTool.o
GENERATED += $(OBJDIR)/RAMInfo.o
GENERATED += $(OBJDIR)/SaveFileDialog.o
GENERATED += $(OBJDIR)/Scene.o
GENERATED += $(OBJDIR)/SelectFolderDialog.o
GENERATED += $(OBJDIR)/SystemAndHardwareInfoTool.o
GENERATED += $(OBJDIR)/ToolsScene.o
GENERATED += $(OBJDIR)/TripleDES.o
GENERATED += $(OBJDIR)/Twofish.o
GENERATED += $(OBJDIR)/ViewEncryptionScene.o
GENERATED += $(OBJDIR)/Window.o
GENERATED += $(OBJDIR)/XOREncryptionTool.o
GENERATED += $(OBJDIR)/pch.o
OBJECTS += $(OBJDIR)/AES.o
OBJECTS += $(OBJDIR)/Algorithm.o
OBJECTS += $(OBJDIR)/Application.o
OBJECTS += $(OBJDIR)/Base64.o
OBJECTS += $(OBJDIR)/Blowfish.o
OBJECTS += $(OBJDIR)/CLI.o
OBJECTS += $(OBJDIR)/CPUInfo.o
OBJECTS += $(OBJDIR)/ChaCha20Poly1305.o
OBJECTS += $(OBJDIR)/Clipboard.o
OBJECTS += $(OBJDIR)/Config.o
OBJECTS += $(OBJDIR)/Cursor.o
OBJECTS += $(OBJDIR)/Database.o
OBJECTS += $(OBJDIR)/DecryptFileScene.o
OBJECTS += $(OBJDIR)/DecryptTextScene.o
OBJECTS += $(OBJDIR)/ENV.o
OBJECTS += $(OBJDIR)/EncryptFileScene.o
OBJECTS += $(OBJDIR)/EncryptTextScene.o
OBJECTS += $(OBJDIR)/GZip.o
OBJECTS += $(OBJDIR)/HashingTool.o
OBJECTS += $(OBJDIR)/IDEA.o
OBJECTS += $(OBJDIR)/ImGuiImpl.o
OBJECTS += $(OBJDIR)/ImGuiRenderer.o
OBJECTS += $(OBJDIR)/Input.o
OBJECTS += $(OBJDIR)/LoadingScene.o
OBJECTS += $(OBJDIR)/Logger.o
OBJECTS += $(OBJDIR)/Main.o
OBJECTS += $(OBJDIR)/MainMenuScene.o
OBJECTS += $(OBJDIR)/MessageBox.o
OBJECTS += $(OBJDIR)/MyEncryptionsScene.o
OBJECTS += $(OBJDIR)/Notification.o
OBJECTS += $(OBJDIR)/OpenFileDialog.o
OBJECTS += $(OBJDIR)/PasswordGeneratorTool.o
OBJECTS += $(OBJDIR)/RAMInfo.o
OBJECTS += $(OBJDIR)/SaveFileDialog.o
OBJECTS += $(OBJDIR)/Scene.o
OBJECTS += $(OBJDIR)/SelectFolderDialog.o
OBJECTS += $(OBJDIR)/SystemAndHardwareInfoTool.o
OBJECTS += $(OBJDIR)/ToolsScene.o
OBJECTS += $(OBJDIR)/TripleDES.o
OBJECTS += $(OBJDIR)/Twofish.o
OBJECTS += $(OBJDIR)/ViewEncryptionScene.o
OBJECTS += $(OBJDIR)/Window.o
OBJECTS += $(OBJDIR)/XOREncryptionTool.o
OBJECTS += $(OBJDIR)/pch.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Enigma
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Enigma
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/AES.o: Source/Algorithm/AES/AES.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Algorithm.o: Source/Algorithm/Algorithm.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Blowfish.o: Source/Algorithm/Blowfish/Blowfish.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ChaCha20Poly1305.o: Source/Algorithm/ChaCha20Poly1305/ChaCha20Poly1305.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IDEA.o: Source/Algorithm/IDEA/IDEA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TripleDES.o: Source/Algorithm/TripleDES/TripleDES.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Twofish.o: Source/Algorithm/Twofish/Twofish.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CPUInfo.o: Source/Analytics/Hardware/CPU/CPUInfo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RAMInfo.o: Source/Analytics/Hardware/RAM/RAMInfo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Application.o: Source/Application/Application.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CLI.o: Source/CLI/CLI.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Config.o: Source/Config/Config.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Database.o: Source/Database/Database.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuiImpl.o: Source/GUI/ImGuiImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuiRenderer.o: Source/GUI/ImGuiRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Input.o: Source/Input/Input.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Logger.o: Source/Logger/Logger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Main.o: Source/Main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DecryptFileScene.o: Source/Scenes/DecryptFileScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DecryptTextScene.o: Source/Scenes/DecryptTextScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EncryptFileScene.o: Source/Scenes/EncryptFileScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EncryptTextScene.o: Source/Scenes/EncryptTextScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LoadingScene.o: Source/Scenes/LoadingScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MainMenuScene.o: Source/Scenes/MainMenuScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MyEncryptionsScene.o: Source/Scenes/MyEncryptionsScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Scene.o: Source/Scenes/Scene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/HashingTool.o: Source/Scenes/ToolsScene/HashingTool.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PasswordGeneratorTool.o: Source/Scenes/ToolsScene/PasswordGeneratorTool.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SystemAndHardwareInfoTool.o: Source/Scenes/ToolsScene/SystemAndHardwareInfoTool.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ToolsScene.o: Source/Scenes/ToolsScene/ToolsScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/XOREncryptionTool.o: Source/Scenes/ToolsScene/XOREncryptionTool.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ViewEncryptionScene.o: Source/Scenes/ViewEncryptionScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Clipboard.o: Source/System/Clipboard/Clipboard.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MessageBox.o: Source/System/Dialogs/MessageBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/OpenFileDialog.o: Source/System/Dialogs/OpenFileDialog.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SaveFileDialog.o: Source/System/Dialogs/SaveFileDialog.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SelectFolderDialog.o: Source/System/Dialogs/SelectFolderDialog.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ENV.o: Source/System/ENV/ENV.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Notification.o: Source/System/Notification/Notification.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Base64.o: Source/Utility/Base64.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GZip.o: Source/Utility/GZip.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Cursor.o: Source/Window/Cursor/Cursor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Window.o: Source/Window/Window.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pch.o: Source/pch.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif