# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw_config = debug
  glad_config = debug
  imgui_config = debug
  spdlog_config = debug
  pfd_config = debug
  stb_image_config = debug
  cryptopp_config = debug
  catch2_config = debug
  Enigma_config = debug

else ifeq ($(config),release)
  glfw_config = release
  glad_config = release
  imgui_config = release
  spdlog_config = release
  pfd_config = release
  stb_image_config = release
  cryptopp_config = release
  catch2_config = release
  Enigma_config = release

else ifeq ($(config),dist)
  glfw_config = dist
  glad_config = dist
  imgui_config = dist
  spdlog_config = dist
  pfd_config = dist
  stb_image_config = dist
  cryptopp_config = dist
  catch2_config = dist
  Enigma_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glfw glad imgui spdlog pfd stb_image cryptopp catch2 Enigma

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: catch2 cryptopp glad glfw imgui pfd spdlog stb_image

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/glfw -f Makefile config=$(glfw_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/glad -f Makefile config=$(glad_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/imgui -f Makefile config=$(imgui_config)
endif

spdlog:
ifneq (,$(spdlog_config))
	@echo "==== Building spdlog ($(spdlog_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/spdlog -f Makefile config=$(spdlog_config)
endif

pfd:
ifneq (,$(pfd_config))
	@echo "==== Building pfd ($(pfd_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/pfd -f Makefile config=$(pfd_config)
endif

stb_image:
ifneq (,$(stb_image_config))
	@echo "==== Building stb_image ($(stb_image_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/stb_image -f Makefile config=$(stb_image_config)
endif

cryptopp:
ifneq (,$(cryptopp_config))
	@echo "==== Building cryptopp ($(cryptopp_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/cryptopp -f Makefile config=$(cryptopp_config)
endif

catch2:
ifneq (,$(catch2_config))
	@echo "==== Building catch2 ($(catch2_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/catch2 -f Makefile config=$(catch2_config)
endif

Enigma: glfw glad imgui spdlog stb_image cryptopp catch2
ifneq (,$(Enigma_config))
	@echo "==== Building Enigma ($(Enigma_config)) ===="
	@${MAKE} --no-print-directory -C . -f Enigma.make config=$(Enigma_config)
endif

clean:
	@${MAKE} --no-print-directory -C Dependencies/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/spdlog -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/pfd -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/stb_image -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/cryptopp -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/catch2 -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Enigma.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   glad"
	@echo "   imgui"
	@echo "   spdlog"
	@echo "   pfd"
	@echo "   stb_image"
	@echo "   cryptopp"
	@echo "   catch2"
	@echo "   Enigma"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"