# Enigma Build workflow task for linux & windows
name: build

# build on pushs and pull requests on master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# platform tasks
jobs:

  ###=== WINDOWS ===###
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [Win32, x64]

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '16.8' #using vs 16.8.3 in my local machine Help -> About Microsoft Visual Studio

      - name: Generate Project Files
        run: .\Premake\Windows\premake5.exe vs2019 --file=premake5.lua

      - name: Build Solution
        run: msbuild Enigma.sln -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo
