name: build-windows-msvc-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  WindowsMSVCTests:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [ x64 ]
        build-platform: [ x64 ]

    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.9.6' # Stable release	2022 17.9.6 / 15 April 2024
          vs-prerelease: true
          msbuild-architecture: x64

      - name: Calculate hash sum of test_data\lorem_ipsum.txt files
        run: |
          powershell Get-FileHash tests\test_data\lorem_ipsum.txt -Algorithm SHA256
          powershell Get-FileHash tests\test_data\lorem_ipsum.txt -Algorithm SHA512

      - name: Generate Visual Studio 17 2022 Solution
        run: |
          mkdir build && cd build
          cmake .. -G"Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DENIGMA_ENABLE_TESTS=ON

      - name: Display tree structure of PRE build
        run: tree /f /a build

      - name: Build EnigmaTests Solution
        run: msbuild build\tests\EnigmaTests.vcxproj -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo

      - name: Display tree structure of POST build
        run: tree /f /a build

      - name: Run EnigmaTests
        run: build\tests\Release\EnigmaTests.exe