name: build-windows-mingw

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  WindowsMinGW:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [Win32, x64]

    defaults:
      run:
        shell: cmd
     
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: Ensure deps are installed
      run: |
        cmake --version
        make --version
        g++ --version

    - name: Generate Project Makefiles
      run: |
        md build && cd build
        cmake .. -G"Unix Makefiles" -A x64 -DCMAKE_BUILD_TYPE=Release -DENIGMA_ENABLE_TESTS=OFF -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build Enigma
      run: cd build && make -j%NUMBER_OF_PROCESSORS%

    - name: Install Enigma
      run: cd build  && make install
# TODO
#    - name: Run Enigma
#      run: Enigma --version
      
# todo    make test if -DENIGMA_ENABLE_TESTS=ON