# Enigma Build workflow task for linux & windows
name: build-windows

# build on pushs and pull requests on master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [Win32, x64]

    defaults:
      run:
        shell: cmd
     
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: Ensure deps are installed
      run: |
        cmake --version
        make --version

    - name: Generate Project Makefiles
      run: |
        md build && cd build
        cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build Enigma
      run: cd build && make -j%NUMBER_OF_PROCESSORS%

    - name: Run Enigma
      run: cd build && Enigma.exe --version
      
# todo    make test if -DENIGMA_ENABLE_TESTS=ON