# Enigma Static Analysis task using CppCheck
# https://github.com/marketplace/actions/cppcheck-action
name: static-analysis

# analyse on pushs and pull requests on master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # CppCheck analysis task
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_library: disable
          skip_preprocessor: disable
          enable: performance,portability,warning
          exclude_check: ./Dependencies/
          inconclusive: disable
          inline_suppression: disable
          force_language: c++
          force: enable
          max_ctu_depth: 12
          platform: unspecified
          std: c++17
          output_file: ./CppCheckReport.txt
          
      # Report generating task
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' # your branch name goes here